// Generated by CoffeeScript 1.7.1
(function() {
  var localService, log, ulti;

  if (typeof self === 'undefined') {
    ulti = require('./../ulti.js');
  } else {
    ulti = self.ulti;
  }

  localService = function(dir_path) {
    this.dir_path = dir_path;
    return this;
  };

  localService.prototype.generate = function(parser, reparse) {
    var _this;
    if (reparse == null) {
      reparse = false;
    }
    _this = this;
    return ulti.fileWalk(this.dir_path, function(file_path) {
      var content, fs, item, parse_result, _i, _len, _results;
      fs = require('fs');
      content = fs.readFileSync(file_path);
      parse_result = parser(file_path, content);
      _results = [];
      for (_i = 0, _len = parse_result.length; _i < _len; _i++) {
        item = parse_result[_i];
        if (!reparse && ulti.existLocalCache(_this.type, encodeURIComponent(file_path))) {
          continue;
        }
        _results.push(ulti.dump(_this.type, encodeURIComponent(file_path), item.value));
      }
      return _results;
    });
  };

  localService.prototype.get = function(file_path, type, cb) {
    return ulti.load(type, encodeURIComponent(file_path), cb);
  };

  module.exports.localService = localService;

  log = function() {};

  log = ulti.log;

}).call(this);

//# sourceMappingURL=local.map
